### PR TITLE
fix(build): stats script for win32

### LINKED ISSUE #302: [Bug] Script failing to generate the i18n and assets sizes while building
I tried the branch [288-bundle-sizes-splash-progress](https://github.com/sugarlabs/musicblocks-v4/tree/288-bundle-sizes-splash-progress) (by @meganindya) to test the code and found one issue with that.

Note: I'm using `Windows 10 OS` that means `win32` platform. The issue isn't happening for `linux` and `darwin` platform as confirmed by @meganindya

I ran `npm run build` and checked the generated `dist/stats.json` file data.
However, I found the `i18n` and `assets` data to be missing.

```json
{
  "i18n": {},
  "assets": {},
  "modules": { "menu": 1394, "singer": 226021, "editor": 35200, "painter": 219016 }
}
```

I double checked to make sure the data is actually present in the `i18n` and `assets` dirMaps, and found that there is some data for both keys.

I then deep dived into the functions and how the data is getting generated and found the bug.

Firstly, when we are saving the `VisualizerData` into the `dist/stats.json` file, we are getting the Absolute Paths of the files inside the `id` of `nodeMetas`.

The `path` module works differently for the `win32` based systems than of `linux` or `darwin`. More info can be found here: [https://nodejs.org/api/path.html#windows-vs-posix](https://nodejs.org/api/path.html#windows-vs-posix)

Here is a glimpse of the generated `VisualizerData` with the `AST (Abstract syntax tree)` information.

```json
{
  "version": 2,
  "tree": {},
  "nodeParts": {},
  "nodeMetas": {
    "57d3-1762": {
      "id": "\u0000commonjs-dynamic-modules",
      "moduleParts": {
        "assets/_commonjs-dynamic-modules-302442b1.js": "57d3-1763"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-2830"
        },
        {
          "uid": "57d3-1992"
        },
        {
          "uid": "57d3-2006"
        }
      ]
    },
    "57d3-1764": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/events/index.ts",
      "moduleParts": {
        "assets/index-97cad2bf.js": "57d3-1765"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-2034"
        },
        {
          "uid": "57d3-1796"
        },
        {
          "uid": "57d3-2848"
        }
      ]
    },
    "57d3-1766": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/i18n/lang/en.ts",
      "moduleParts": {
        "assets/lang.en-a09fe94b.js": "57d3-1767"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1782"
        }
      ],
      "isEntry": true
    },
    "57d3-1768": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/i18n/lang/es.ts",
      "moduleParts": {
        "assets/lang.es-5dc320b5.js": "57d3-1769"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1782"
        }
      ],
      "isEntry": true
    },
    "57d3-1770": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/components/index.ts",
      "moduleParts": {
        "assets/index-0b306afc.js": "57d3-1771"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1778"
        },
        {
          "uid": "57d3-2104"
        }
      ]
    },
    "57d3-1772": {
      "id": "\u0000vite/preload-helper",
      "moduleParts": {
        "assets/dynamic-import-helper-cd46bf53.js": "57d3-1773"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1778"
        },
        {
          "uid": "57d3-1782"
        },
        {
          "uid": "57d3-1834"
        },
        {
          "uid": "57d3-1830"
        }
      ]
    },
  },
  "env": {
    "rollup": "3.10.1"
  },
  "options": {
    "gzip": true,
    "brotli": false,
    "sourcemap": false
  }
}
```

That's why `id.startsWith(prefix)` is failing in [scripts/stats/index.ts#L55](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L55) and it is basically returning an empty array.

One simple solution is to put a platform check using `process.platform` and detect if the platform is `win32`; and use `id.includes(prefix)` instead of `id.startsWith(prefix)`, but then again we need to fix the logic to structure the key in [scripts/stats/index.ts#L57](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L57) to actually remove the root path from the `Absolute Path` and then replace the `prefix` with an empty string to only get the fileName as the key.

More discussion and context can be found [here](https://github.com/sugarlabs/musicblocks-v4/issues/288#issuecomment-1399603559)

Related issue: #288 

CC @meganindya

### PR DESCRIPTION
**Pull request by niloysikdar**
Fixed the stats data generating script for `win32` platform as discussed [here](https://github.com/sugarlabs/musicblocks-v4/issues/302)

closes #302 

Signed-off-by: Niloy Sikdar <niloysikdar30@gmail.com>

### CODE REVIEW

File: tools/scripts/stats/index.ts [hunk 1]
```diff
@@ -51,6 +51,17 @@ export function getStats(data: VisualizerData): {
...
+            return Object.values(data.nodeMetas)
+                .filter(({ id }) => id.includes(prefix))
+                .map<[string, number]>(({ id, moduleParts }) => [
+                    id.split(prefix).slice(-1)[0],
+                    Object.values(moduleParts)
+                        .map((moduleId) => data.nodeParts[moduleId].gzipLength)
+                        .reduce((a, b) => a + b),
+                ]);
+        }
+
```
Comment (meganindya) [inline tools/scripts/stats/index.ts]: this is code repetition.

instead just change the filter line to
`filter(({ id }) => process.platform === 'win32' ? id.includes(prefix) : id.startsWith(prefix))`

**Review by meganindya — CHANGES_REQUESTED** [review]

File: tools/scripts/stats/index.ts (hunk 1 above)
Comment (niloysikdar) [reply tools/scripts/stats/index.ts]: Done

**Comment by niloysikdar** [comment]
Done, can you check once?

**Review by meganindya — APPROVED** [review]
looks alright
